modules/word/views.py
from flask import render_template, abort, url_for, current_app, g, request, redirect
from jinja2 import TemplateNotFound
from flask import Blueprint
from core import app
from modules.word.models import Word
from datetime import datetime
import json
import string

bp_word = Blueprint('bp_word', __name__, template_folder="templates")

@bp_word.route("/")
def home():
	"""
	business logic for home page
	"""
	try:
		word = Word(g.user["_id"])
		return render_template("home.html", words = word.find_popular(10))
	except TemplateNotFound:
		app.logger.error("template word/home.html not found")
		abort(404)

@bp_word.route("/new")
def new_words():
	"""
	business logic for home page
	"""
	try:
		word = Word(g.user["_id"])
		return render_template("home.html", words = word.find_new(10))
	except TemplateNotFound:
		app.logger.error("template word/home.html not found")
		abort(404)

@bp_word.route("/random")
def random_words():
	"""
	business logic for home page
	"""
	try:
		word = Word(g.user["_id"])
		return render_template("home.html", words = word.find_random(10))
	except TemplateNotFound:
		app.logger.error("template word/home.html not found")
		abort(404)


@bp_word.route("/start-with/<alphabet>")
def alpha(alphabet):
	"""
	business logic for home page
	"""
	try:
		word = Word(g.user["_id"])
		return render_template("home.html", words = word.find_startswith(alphabet.lower(),10))
	except TemplateNotFound:
		app.logger.error("template word/home.html not found")
		abort(404)

@bp_word.route("/add", methods=["GET"])
def show_add_form():
	"""
	Shows add word form
	"""
	try:
		return render_template("add_word.html")
	except TemplateNotFound:
		app.logger.error("template word/add_word.html not found")
		abort(404)

@bp_word.route("/add", methods=["POST"])
def add_word():
	"""
	add slang to database
	"""
	word = Word(g.user["_id"])
	try:
		data = {
			'language': request.form.get("language"),
			'local': request.form.get("local"),
			'phrase' : request.form.get("phrase"),
			'definition' : request.form.get("definition"),
			'example' : request.form.get("example"),
			'tags' : [tag.strip() for tag in request.form.get("tags").split(",")],
			'likes' : [],
			'dislikes' : [],
			'likes_count' : 0,
			'dislikes_count' : 0,
			'views' : [],
			'views_count' : 0,
			'date_added' : datetime.utcnow().isoformat(),
			'status' : Word.STATUS["approved"],
			'user_id' : g.user["_id"],
			'user_nick' : "",
			'random' : word.get_random_value(int, 5)
		}
		word_id = word.insert_word(data)
		if word_id is None:
			return render_template("add_word.html", error="Error(s) occured in validation", errors = word.errors)
		else:
			return redirect(url_for("bp_word.show_add_form", success="Word inserted successfully."))
	except KeyError as keys:
		return render_template("add_word.html", error="Required form field missing: " + keys[0])
	except Exception as errors:
		return render_template("add_word.html", error="Unknown error occured. Contact site admin to report this." + json.dumps(errors.args))


app.register_blueprint(bp_word)

modules/word/templates/add_word.html
{% extends "base.html" %}
{% block custom_styles %}
	{% if request.form.get("language", "english") != "english" %} 
	<style>
		.foreign-lang{
			display: block;
		}
		.english-lang{
			display: none;
		}
	</style>
	{% endif %}
{% endblock %}

{% block side_menu %}
{% endblock %}

{% block sub_menu %}
{% endblock %}

{% block content_container_class %}col-lg-12{% endblock %}

{% block content %}
<form role="form" method="post">
	{% if request.args.get("success") %}
	<div class="alert alert-success alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		{{request.args.get("success")}}
	</div>
	{% endif %}
	{% if error %}
	<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		{{error}}
		{% if errors %}
		<ul>
			{% for field, message in errors.iteritems() %}
				<li><strong>{{field|capitalize}}:</strong> {{message}}</li>
			{% endfor %}
		</ul>
		{% endif %}
	</div>
	{% endif %}
	<fieldset>
		<legend><strong>{{_("Submit a new slang")}}</strong></legend>
		<div class="form-group">
			<label for="language">{{_("This slang is in")}}</label>
			<select name="language" class="form-control" id="language">
				<option {% if request.form.get("language") == "english" %} selected {% endif %} value="english">English</option>
				<option {% if request.form.get("language") == "arabic" %} selected {% endif %} value="arabic">Arabic</option>
				<option {% if request.form.get("language") == "urdu" %} selected {% endif %} value="urdu">Urdu</option>
			</select>
		</div>
		<div class="row">
			<div class="col-lg-6">
				<div class="form-group foreign-lang {% if errors and errors["local"] %}has-error{% endif %}">
					{% autoescape off %}
					<label for="local">{{_("It's written in %(language)s as", language='<span id="lang_text">' + request.form.get("language","Japanese") + '</span>')}}</label>
					{% endautoescape %}
					<input type="text" class="form-control" id="local" name="local" value="{{request.form["local"]}}">
					<p class="help-block foreign-lang">ファック ({{_("Fuck in Japanese")}})</p>
				</div>
			</div>
		</div>
		<div class="form-group {% if errors and errors["phrase"] %}has-error{% endif %}">
			{% autoescape off %}
			<label class="foreign-lang" for="phrase">{{_("Pronunciation of %(word)s in English can be best written as", word='<span class="eng_pron">ファック</span>')}}</label>
			<label class="english-lang" for="phrase">{{_("Word")}}</label>
			{% endautoescape %}
			<input value="{{request.form["phrase"]}}" type="text" class="form-control" name="phrase" id="phrase">
			<p class="help-block foreign-lang">{{_("Fakku (Pronunciation of ファック)")}}</p>
		</div>
		<div class="form-group {% if errors and errors["definition"] %}has-error{% endif %}">
			<label for="definition">{{_("Definition")}}</label>
			<textarea class="form-control" name="definition" id="definition" rows="5">{{request.form["definition"]}}</textarea>
		</div>

		<div class="form-group {% if errors and errors["tags"] %}has-error{% endif %}">
			<label for="tags">{{_("Similar slangs:")}}</label>
			<input type="text" class="form-control" name="tags" id="tags" value="{{request.form["tags"]}}">
			<p class="help-block">{{_("Commma separated list of similar slangs")}}</p>
		</div>
		<div class="form-group {% if errors and errors["example"] %}has-error{% endif %}">
			<label for="example">{{_("Example(s):")}}</label>
			<textarea rows="5" class="form-control" name="example" value="{{request.form["example"]}}" id="example"></textarea>
			<p class="help-block foreign-lang">{{_("男はねえ、あなたをファック (Hey man, Fuck you)")}}</p>
		</div>
		<hr/>
		<p class="help-block">{{_("We recommend that you register after submission so you can take credit for your submission. Your submission will be reviewed before acceptance. You will be notified by email if you are registered.")}}</p>
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</fieldset>
</form>
{% endblock %}

modules/word/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	{% for word in words %}
	<div class="col-md-6">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">
		    	<a href="#">{{word["phrase"]}} {%if word["local"] %}({{word["local"]}}) {% endif %} </a>
			    <span class="vote">
			    	<a href="#"><span class="glyphicon glyphicon-arrow-up"></span></a>
			    	&nbsp;{{word["likes_count"]}}&nbsp;
			    	<a href="#"><span class="glyphicon glyphicon-arrow-down"></span></a>
			    	&nbsp;{{word["dislikes_count"]}}
			    </span>
		    </h3>
		  </div>
		  <div class="panel-body">
		    <dl>
			  <dt>{{_("Definition")}}</dt>
			  <dd>{{word["definition"]}}</dd>
			</dl>
			<dl>
			  <dt>{{_("Examples")}}</dt>
			  <dd><em>{{word["example"]}}</em></dd>
			</dl>
			<a href="#">{{_("More examples and defintions...")}}</a>
		  </div>
		</div>
	</div>
	{% endfor %}
	{% if not words or words.count() == 0 %}
		{% if "alphabet" in  url_args(request.path) %}
		<div class="col-lg-12 clear">
			<div class="jumbotron">
			  <h1>{{_("Hey, there!")}}</h1>
			  <p>{{_("Nobody has defined a word in this category yet. Become the first one to define a slang starting with \"%(alphabet)s\".", alphabet=url_args(request.path)["alphabet"].upper())}}</p>
			  <p><a class="btn btn-primary btn-lg" role="button" href="{{url_for("bp_word.add_word")}}">{{_("Define Now")}}</a></p>
			</div>
		</div>
		{% else %}
		<div class="col-lg-12 clear">
			<div class="jumbotron">
			  <h1>{{_("Hey, there!")}}</h1>
			  <p>{{_("Nobody has defined any word in this category yet. Become the first one to define a slang here.")}}</p>
			  <p><a class="btn btn-primary btn-lg" role="button" href="{{url_for("bp_word.add_word")}}">{{_("Define Now")}}</a></p>
			</div>
		</div>
		{% endif %}
	{% endif %}

</div>
{% endblock %}